version: "3"
services:
       carritosad:
           container_name: sem2sadcontainer
           image: jeyaesig/carritosad
           build: .
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             ports:
               - '27017:27017'
